### ISSUE TITLE
Error when interpolating variables as a substring of an attribute

### ISSUE THREAD

**Issue by acarapetis** [asyncLiz/minify-html-literals#1]
If I run this test:

```
require('minify-html-literals').minifyHTMLLiterals(
	'html`<p style="color: ${color}"></p>`'
);
```

Then I get this error:
```
Error: splitHTMLByPlaceholder() must return same number of strings as template parts
```

Replacing "color: ${color}" with "${color}" makes the error go away.

**Comment by acarapetis** [comment]
Setting `removeAttributeQuotes: false` in `minifyOptions` would fix this if not for the presence of a semicolon in `defaultStrategy.getPlaceholder()`.

**Comment by asyncLiz** [comment]
Thanks for finding that bug! I added a test case for it and published 1.1.2 that fixes it.

**Comment by neuronetio** [comment]
I still have this issue in `1.2.5` but I've got multiple style properties in `style` tag.

HTML: 
```html
<div style="left: ${left}px; top: ${top}px;"></div>
```

**Comment by davidfilkins** [comment]
> I still have this issue in `1.2.5` but I've got multiple style properties in `style` tag.
> 
> HTML:
> 
> ```
> <div style="left: ${left}px; top: ${top}px;"></div>
> ```
> 
> But this code works:
> 
> ```
> <div style="left: ${left+'px'}; top: ${top+'px'};"></div>
> ```

This saved me hours of digging. Thanks @neuronetio!
