### ISSUE TITLE
clean-css strips off svg styles like r: 2px

### ISSUE THREAD

**Issue by s4san** [asyncLiz/minify-html-literals#10]
I have a code block in lit-html like so,

```
css`
circle {
  r: 2px;
}
`
```

But when minifying the file using the plugin, it strips off the circle style completely deeming it to be invalid css due to `clean-css` plugin

For now, I have solved this issue by following the advice [here](https://stackoverflow.com/a/44857133/2360304) but this results in the CSS not being minified. I know that the issue is not with this plugin per se, but just wondering if you have any thoughts on how to solve this.

Thanks!

**Comment by asyncLiz** [comment]
I'm not sure the best way to go around clean-css ignoring invalid properties, but you can pass options to clean-css in this plugin.

```js
minifyHTMLLiterals(template, {
  minifyOptions: {
    minifyCSS: {
      level: {
        2: {
          skipProperties: ['r']
        }
      }
    }
  }
});
```
My advice would be to find a combination of properties and/or comments that work best for you.
