### ISSUE TITLE
Returns null instead of `{error}`

### ISSUE THREAD

**Issue by WebReflection** [asyncLiz/minify-html-literals#11]
I'd love to use this optimizer in conjunction with other libraries, but `minifyHTMLLiterals(validJS)` returns `null`, where `validJS` can be the source code of any file.

I've tried to pass a `filename` too but basically this always returns `null`.

Any idea what am I doing wrong? Is this supposed to return `null` when the file has no `html` template literals in it? If that's the case, what does it return in case the file contains template literals with html in it?

Thanks.

**Comment by asyncLiz** [comment]
If there's nothing to minify, it'll return `null`. From the documentation:

```
@returns the minified code, or null if no minification occurred.
```

If it minifes the code, it'll return a [Result](https://github.com/asyncLiz/minify-html-literals/blob/33866eb8a936a0439b0b78e33a809f58a35e6cbb/src/minifyHTMLLiterals.ts#L161-L170) object.

**Comment by WebReflection** [comment]
uhm ... may I ask how come that's the case? ergonomics are a bit awkward, i.e.

```js
// this throws
const {error, code} = minifyHTMLLiterals(code);

// this is a bit awkward
const maybeNull = minifyHTMLLiterals(code);
saveContent(maybeNull && !maybeNull.error ? maybeNull.code : code);
```

Wouldn't it be simpler to just return code as is as _Result_ object?

**Comment by WebReflection** [comment]
P.S. since we are here, is the `filename` really mandatory? it doesn't warn me, and I don't want to use a file name as it's all runtime without files access, thanks.

**Comment by asyncLiz** [comment]
This library was primarily built for [rollup-plugin-minify-html-literals](https://github.com/asyncLiz/rollup-plugin-minify-html-literals). In rollup, if a plugin returns `null`, that indicates that no transformations should be made, which is why this library does that.

The [filename is optional](https://github.com/asyncLiz/minify-html-literals/blob/33866eb8a936a0439b0b78e33a809f58a35e6cbb/src/minifyHTMLLiterals.ts#L51). The downside is that the generated sourcemap will not point to the right file.

**Comment by asyncLiz** [comment]
Additionally, `error` is not a property of the result. If there is an error, it will be thrown.

```js
try {
  const result = minifyHTMLLiterals(code);
  if (result) {
    // minified
    const { code, map } = result;
  } else {
    // not minified
  }
} catch (error) {
  console.log(error);
}
```

**Comment by WebReflection** [comment]
> The filename is optional.

![Screenshot from 2020-05-08 19-59-06](https://user-images.githubusercontent.com/85749/81434446-6f680080-9166-11ea-8f33-2565a1e69b98.png)

> Additionally, error is not a property of the result. If there is an error, it will be thrown.

fair enough.

I guess my last question would be: is there a way to not bother with the `map` ? I guess not passing a `filename` would do, but it's not super clear in the README.

I was going to file a PR but I wouldn't know if it's _Required for source map_ or simply optional.

**Comment by asyncLiz** [comment]
Looks like the readme is outdated, it's not required. If no filename is provided, the library will give [an empty string](https://github.com/asyncLiz/minify-html-literals/blob/33866eb8a936a0439b0b78e33a809f58a35e6cbb/src/minifyHTMLLiterals.ts#L345) as the filename to the sourcemap generated.

If you don't want the map, you can just ignore it.

```js
const result = minifyHTMLLiterals(code);
const minified = result ? result.code : code;
```

Let me know if that doesn't work.

**Comment by WebReflection** [comment]
Thanks!

**Comment by WebReflection** [comment]
Sorry for the late question, does this reason well to you?

```js
        try {
          const mini = minifyHTMLLiterals(content);
          const {code, error} = terser.minify(
            mini ? mini.code : content,
            terserArgs
          );
          if (error)
            throw error;
          else
            res(code);
        }
        catch (error) {
          rej(error);
        }
```

**Comment by asyncLiz** [comment]
Makes sense to me
