### ISSUE TITLE
parts are concattenated

### ISSUE THREAD

**Issue by bennypowers** [asyncLiz/minify-html-literals#26]
Thanks for publishing this awesome package.

-----

Consider this repl:

https://repl.it/@bennypowers/minify-html-literals-css-shadow-parts-concat-bug#index.js

input:
```js
html`<h1> hi </h1>`;
css`
#shadow::part(a b c) {
  color: red;
}
```

CSS-unminified output:
```js
html`<h1>hi</h1>`;
css`
#shadow::part(a b c) {
  color: red;
}
`
```

## Actual
CSS-minified output:
```js
html`<h1>hi</h1>`;
css`#shadow::part(abc){color:red}`
```
## Expected
CSS-minified output:
```js
html`<h1>hi</h1>`;
css`#shadow::part(a b c){color:red}`
```
this package should maintain the part selector `a b c`.

I'm pretty sure this is an upstream issue with CleanCSS

**Comment by bennypowers** [comment]
workaround:

workaround:
1. remove `postcss-clean` from `postcss.config.js`
2. use `minifyLitHtml` rollup plugin like so : `minifyLitHtml({ options: { shouldMinifyCSS() { return false; } } })`
3. use `rollup-plugin-styles` like so: `styles({ mode: 'emit', minimize: true })`

**Comment by asyncLiz** [comment]
I added a patch to restore space-separated pseudo class selectors while waiting on https://github.com/jakubpawlowicz/clean-css/issues/996

**Comment by bennypowers** [comment]
see also https://github.com/leodido/postcss-clean/issues/39
