### ISSUE TITLE
Update to Terser to Resolve ReDoS Vulnerability

### ISSUE THREAD

**Issue by timbomckay** [asyncLiz/minify-html-literals#52]
The [`html-minifier` package](https://www.npmjs.com/package/html-minifier) hasn't been updated for nearly 4 years and has a [ReDoS vulnerability](https://github.com/kangax/html-minifier/issues/1135). Terser has forked the repo and is actively maintaining it under [`html-minifier-terser`](https://www.npmjs.com/package/html-minifier-terser).

Can this get updated to use the maintained package from Terser?

**Comment by timbomckay** [comment]
To anyone stumbling upon this issue I did discover [`minify-literals`](https://www.npmjs.com/package/minify-literals) is using the newly maintained terser dependency, along with a [rollup plugin](https://www.npmjs.com/package/rollup-plugin-minify-template-literals).

**Comment by asyncliz** [comment]
Closing as fixed in #57
