### ISSUE TITLE
Can this plugin be extended to minify `svg` as well?

### ISSUE THREAD

**Issue by s4san** [asyncLiz/minify-html-literals#9]
Thanks a ton for creating this plugin it has been incredibly helpful! I noticed that when minifying it looks for template strings created with `html` or `css` functions and minifies them. Can this be extended to minify template strings created using the `svg` function in `lit-html` as well? That would be really helpful!

Thanks again!

**Comment by asyncLiz** [comment]
I think so! 😊

**Comment by asyncLiz** [comment]
Fixed in v1.3.0
